#/usr/bin/python3
#coding:utf-8

#*******************************************************************************
# 让我们用一个例子来看看try的机制：
#*******************************************************************************
n = int(input('input integer:'))
try:
    print('try...')
    r = 10 / n
    print('result:',r)
except ZeroDivisionError as e:
    print('except:',e)
except ValueError as e:
    print('except:',e)
else:
    print('no error')
finally:
    print('finally...')
print('End')

#*******************************************************************************
# 小结
# Python内置的try...except...finally用来处理错误十分方便。出错时，会分析错误信息并定位错误发生的代码位置才是最关键的。
# 程序也可以主动抛出错误，让调用者来处理相应的错误。但是，应该在文档中写清楚可能会抛出哪些错误，以及错误产生的原因。
#*******************************************************************************
